export const customArray = [
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
  {
    name: "a",
    email: "b",
    isApproved: "c",
    id: "d",
    phoneNumber: "e",
    isBlocked: false,
    Business: "g",
    username: "h",
  },
];
